export const data = [
  {
    id: 1,
    category: "машина",
    price: "45 000 000 〒",
    location: "ул. Сыганак 64",
    rooms: "3",
    want: "дом",
    status: true,
  },
  {
    id: 2,
    category: "машина",
    price: "39 000 000 〒",
    location: "Коргалжинское шоссе 6",
    rooms: "2",
    want: "дом",
    status: true,
  },
  {
    id: 3,
    category: "машина",
    price: "38 000 000 〒",
    location: "Улица Анет Баба 13",
    rooms: "2",
    want: "дом",
    status: true,
  },
  {
    id: 4,
    category: "машина",
    price: "33 000 000 〒",
    location: "Сарайшик 5Б",
    rooms: "2",
    want: "дом",
    status: true,
  },
  {
    id: 5,
    category: "машина",
    price: "33 000 000 〒",
    location: "Туркестан 2",
    rooms: "2",
    want: "дом",
    status: true,
  },
  {
    id: 6,
    category: "дом",
    price: "31 500 000 〒",
    location: "Ильяс Омаров 27",
    rooms: "2",
    want: "офис",
    status: true,
  },
  {
    id: 7,
    category: "дом",
    price: "31 500 000 〒",
    location: "Ильяс Омаров 27",
    rooms: "2",
    want: "офис",
    status: true,
  },
  {
    id: 8,
    category: "дом",
    price: "31 500 000 〒",
    location: "Ильяс Омаров 27",
    rooms: "2",
    want: "офис",
    status: true,
  },
  {
    id: 9,
    category: "дом",
    price: "31 500 000 〒",
    location: "Ильяс Омаров 27",
    rooms: "2",
    want: "офис",
    status: true,
  },
  {
    id: 10,
    category: "дом",
    price: "31 500 000 〒",
    location: "Ильяс Омаров 27",
    rooms: "2",
    want: "офис",
    status: true,
  },
  {
    id: 11,
    category: "офис",
    price: "31 500 000 〒",
    location: "Ильяс Омаров 27",
    rooms: "2",
    want: "квартира",
    status: true,
  },
  {
    id: 12,
    category: "офис",
    price: "31 500 000 〒",
    location: "Ильяс Омаров 27",
    rooms: "2",
    want: "квартира",
    status: false,
  },
  {
    id: 13,
    category: "офис",
    price: "31 500 000 〒",
    location: "Ильяс Омаров 27",
    rooms: "2",
    want: "квартира",
    status: true,
  },
  {
    id: 14,
    category: "дом",
    price: "31 500 000 〒",
    location: "Ильяс Омаров 27",
    rooms: "2",
    want: "офис",
    status: true,
  },
];